### ISSUE TITLE
standardise spec retrieval URLs

### ISSUE THREAD

**Issue by ialarmedalien** [kbase/relation_engine#15]
data sources are accessed via `/data_sources` or `/data_sources/name`

collections (and stored queries) are accessed via `/spec/collections` or `/spec/collections?name=...`

since the data on the backend and the retrieval mechanism is so similar, it would make sense to have similarly-structured URLs

**Comment by jayrbolton** [comment]
Closed by #17 ?

**Comment by jayrbolton** [comment]
Closed by #16?

**Comment by ialarmedalien** [comment]
See https://github.com/kbase/relation_engine/blob/develop/relation_engine_server/README.md#get-apiv1data_sources and below for an example of an API that uses the `/{schema_type}/name` format
